name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
      - run: pdm install
      - run: pdm run ruff check src/ tests/
      - run: pdm run pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    env:
      OPENAI_API_KEY: dummy
      GROQ_API_KEY: dummy
      EMBEDDING_PROVIDER: openai
      LLM_PROVIDER: groq
      COLLECTION_DIR: tests/test_data
      COLLECTION_NAME: test_collection
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pdm install
      - run: pdm run pytest
