name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: FAKE
      GROQ_API_KEY: FAKE
      EMBEDDING_PROVIDER: openai
      LLM_PROVIDER: groq
      COLLECTION_DIR: tests/test_data
      COLLECTION_NAME: test_collection

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set test environment variables
        run: |
          echo "GROQ_API_KEY=dummy" >> $GITHUB_ENV
          echo "OPENAI_API_KEY=dummy" >> $GITHUB_ENV

      - name: Install PDM
        run: python -m pip install --upgrade pip pdm

      - name: Install dependencies with PDM
        run: pdm install

      - name: Run tests
        run: pdm run pytest

      - name: Lint with Ruff
        run: |
          pdm run ruff check src/ tests/
